### ISSUE TITLE
npm run start - Module parse failed: Unknown element type in table: 0xNaN

### ISSUE THREAD

**Issue by Jeroendevr** [rustwasm/wasm-pack-template#74]
### Describe the Bug

Following the Game of Life tutorial at [RustWasm](https://rustwasm.github.io/docs/book/game-of-life/hello-world.html) I encounter the following executing 

```log
> create-wasm-app@0.1.0 start
> webpack-dev-server

<i> [webpack-dev-server] Project is running at:
<i> [webpack-dev-server] Loopback: http://localhost:8080/, http://[::1]:8080/
<i> [webpack-dev-server] On Your Network (IPv4): http://10.19.0.143:8080/
<i> [webpack-dev-server] Content not from webpack is served from '/Users/hayer/rust/wasm-game-of-life/www/public' directory
assets by path *.js 286 KiB
  asset bootstrap.js 280 KiB [emitted] (name: main)
  asset index_js.bootstrap.js 6.77 KiB [emitted]
asset b92850567747f7443a45.module.wasm 1.43 KiB [emitted] [immutable]
asset index.html 297 bytes [emitted] [from: index.html] [copied]
runtime modules 31.6 KiB 15 modules
modules by path ./node_modules/ 185 KiB
  modules by path ./node_modules/webpack-dev-server/client/ 81.9 KiB 17 modules
  modules by path ./node_modules/webpack/hot/*.js 5.17 KiB 4 modules
  modules by path ./node_modules/html-entities/lib/*.js 78.9 KiB 4 modules
  ./node_modules/ansi-html-community/index.js 4.16 KiB [built] [code generated]
  ./node_modules/events/events.js 14.5 KiB [built] [code generated]
modules by path ../pkg/ 1.39 KiB (javascript) 1.28 KiB (webassembly)
  ../pkg/wasm_game_of_life.js 203 bytes [built] [code generated]
  ../pkg/wasm_game_of_life_bg.wasm 40 bytes (javascript) 1.28 KiB (webassembly) [built] [code generated] [1 error]
  ../pkg/wasm_game_of_life_bg.js 1.15 KiB [built] [code generated]
modules by path ./*.js 337 bytes
  ./bootstrap.js 279 bytes [built] [code generated]
  ./index.js 58 bytes [built] [code generated]

ERROR in ../pkg/wasm_game_of_life_bg.wasm
Module parse failed: Unknown element type in table: 0xNaN
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
Error: Unknown element type in table: 0xNaN
    at parseTableType (/Users/hayer/rust/wasm-game-of-life/www/node_modules/@webassemblyjs/wasm-parser/lib/decoder.js:1018:13)
    at parseTableSection (/Users/hayer/rust/wasm-game-of-life/www/node_modules/@webassemblyjs/wasm-parser/lib/decoder.js:1274:24)
    at parseSection (/Users/hayer/rust/wasm-game-of-life/www/node_modules/@webassemblyjs/wasm-parser/lib/decoder.js:1406:24)
    at Object.decode (/Users/hayer/rust/wasm-game-of-life/www/node_modules/@webassemblyjs/wasm-parser/lib/decoder.js:1740:25)
    at decode (/Users/hayer/rust/wasm-game-of-life/www/node_modules/@webassemblyjs/wasm-parser/lib/index.js:253:21)
    at WebAssemblyParser.parse (/Users/hayer/rust/wasm-game-of-life/www/node_modules/webpack/lib/wasm-async/AsyncWebAssemblyParser.js:61:19)
    at /Users/hayer/rust/wasm-game-of-life/www/node_modules/webpack/lib/NormalModule.js:1309:19
    at processResult (/Users/hayer/rust/wasm-game-of-life/www/node_modules/webpack/lib/NormalModule.js:938:11)
    at /Users/hayer/rust/wasm-game-of-life/www/node_modules/webpack/lib/NormalModule.js:1036:5
    at /Users/hayer/rust/wasm-game-of-life/www/node_modules/loader-runner/lib/LoaderRunner.js:407:3
 @ ../pkg/wasm_game_of_life.js 1:0-52 4:15-19 5:0-21
 @ ./index.js 1:0-42 3:0-10
 @ ./bootstrap.js 4:0-20

webpack 5.96.1 compiled with 1 error in 189 ms
```

### Steps to Reproduce

```sh
# Step 1
cargo generate --git https://github.com/rustwasm/wasm-pack-template
# Step 2
# give name and cd into project
# Step 3
wasm-pack build
# Step 4
npm init wasm-app www
# Step 5 
cd www
# Step 6
npm install
# Step 7 
# Follow the change of dependencies at https://rustwasm.github.io/docs/book/game-of-life/hello-world.html#using-our-local-wasm-game-of-life-package-in-www
npm run start
```

### Expected Behavior

A successfull build with a [webpage](http://localhost:8080/) with an alert message

### Actual Behavior

See debug log above

### Additional Context

The dependencies on the `cargo.toml` file are quite old. So I also tried with the newest dependencies.

**Comment by Jeroendevr** [comment]
This issue was related to https://github.com/rustwasm/wasm-bindgen/issues/4211

so using rust <= 1.81 or wasm-pack <= 0.2.93 is a workaround at the moment.

**Comment by qwertzui11** [comment]
Some time seemed to have passed.

For me to make the tutorial work I heavily had to update the `webpack` depndencies inside the `www` folder. not sure if it was necessary to update all three packages

```diff
diff --git a/www/package.json b/www/package.json
index 0c6860f..e5f76d9 100644
--- a/www/package.json
+++ b/www/package.json
@@ -31,9 +31,9 @@
   },
   "devDependencies": {
     "hello-wasm-pack": "^0.1.0",
-    "webpack": "^4.29.3",
-    "webpack-cli": "^3.1.0",
-    "webpack-dev-server": "^3.1.5",
+    "webpack": "^5.98.0",
+    "webpack-cli": "^6.0.1",
+    "webpack-dev-server": "^5.2.0",
     "copy-webpack-plugin": "^5.0.0"
   }
 }
diff --git a/www/webpack.config.js b/www/webpack.config.js
index 80ad814..b27bab2 100644
--- a/www/webpack.config.js
+++ b/www/webpack.config.js
@@ -3,6 +3,9 @@ const path = require('path');
 
 module.exports = {
   entry: "./bootstrap.js",
+  experiments: {
+    asyncWebAssembly: true
+  },
   output: {
     path: path.resolve(__dirname, "dist"),
     filename: "bootstrap.js",
```

updating `wasm-bind` did NOT do the trick. However I'm in the beginning of the tutorial, so I kinda have no idea of what I'm doing 😉 

Afterwards the error

```
  opensslErrorStack: [
    'error:03000086:digital envelope routines::initialization error',
    'error:0308010C:digital envelope routines::unsupported'
  ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
```

with the solution `NODE_OPTIONS=--openssl-legacy-provider npm run start` was unnecessary too.

**Comment by GeneralGDA** [comment]
@qwertzui11, you saved my day.

**Comment by tomtvr** [comment]
@qwertzui11 saved me too! Literally spent 2 hours doubting everything in existence.

Any chance there could be a note added on the tutorial docs to prevent other people falling into this trap?

**Comment by sayantn** [comment]
currently simply running `npm audit fix --force` and adding the `asyncWebAssembly` experiment to `webpack` does the deal

**Comment by timmyjose** [comment]
@qwertzui11 Thank you! 🙂
